### PR TITLE
Feature/63 Support Verida Usernames

### PR DESCRIPTION
**Pull request by aurelticot**
Allows to:

- Support Verida Usernames in the URL and the Search feature
- Resolve a Username to a DID, so that the DID can be used when needed (share feature, ...)
- Get the Profile of a Username
- Continue to support DID as an input (in URL and Search)
- Get the Usernames from a DID when the DID is the input
- Prefer use of a Username to a DID (in the UI, in the URL, ...)

Can be tested with 'verida-tahpot-1.vda'

### CODE REVIEW

**Comment by aurelticot** [comment]
Build failing because of `console.debug()` intentionally left in the code while debugging

**Review by tahpot — APPROVED** [review]
Looks great!

Approved.

Should the username be used instead of the DID when sharing the profile link?

**Comment by aurelticot** [comment]
> Should the username be used instead of the DID when sharing the profile link?

@tahpot, yeah, I thought about it.

The Sharing feature merely use the current URL of the page.
So, if a viewer arrives on the profile with a Username in the URL, the shared URL will be with the Username. If they arrives with the DID in the URL, the shared URL will be with the DID.

I guess, the viewer may want to share the URL with DID sometimes (stable with time) rather than the URL with Username (which can be changed).

When it comes to how a viewer arrives on the profile, there are two ways:
- Click a link. In that case, the URL could be with a Username or a DID. There is no alteration or the URL (ie: if it's a DID, there is no redirection to the Username URL)
- Search a DID or Username on Verida One and click on a result item. In that case, the Username URL will be opened even if the viewer searched for a DID (except if the DID doesn't have a registered username obviously).

So, another question is: Should we automatically redirect a DID URL to a Username URL (by extension, the shared URL will always be with the username)?

Or, should we keep as it is currently? (no auto URL redirection DID to Username and shared URL is current one, with either DID or Username)

Or, should we not redirect a DID URL to a Username URL (current behaviour), but use the username in the Sharing feature? (knowing the DID URL can always be shared via the browser itself)

_Note: Overall, if there are several Usernames registered for one DID, currently, the first one on the list is used, the others are currently disregarded._

**Review by nlothian — APPROVED** [review]
Looks good

**Pull request merged**
